### ISSUE TITLE
Add table of competitions

### ISSUE THREAD

**Issue by opohorel** [JEK58/wprs-forecast#19]
Hi, I really love this tool as I can instantly see if the comp is worth attending or even registering to.

The last feature that I miss here is having a table of competitions with its predicted wprs, so I can look through it and compare competitions.

I know that this would be harder to implement as you would have to scrape through the competition hosting sites, gather the dates when the comp takes a place, update the forecast regularly and then remove the comp from the list after it took a place. But maybe for a start have something like a table, sorted by forecasted wprs which comes from the links users input into the tool (something similar to recent queries)

Do you think this is achievable?

**Comment by JEK58** [comment]
This would either involve caching or serious scraping. I'll think about it.
I wanted to not cache too much, so that if someone gets confirmed at a comp you see the now correct result immediately.
In the meantime: There is a currently hidden stats page that gives you some information: https://wprs-forecast.org/stats

I'll come back to this thread if I have some more time or a good idea. Thanks for your feedback!

**Comment by JEK58** [comment]
There is now a recent queries table on the home page.
