### ISSUE TITLE
add range for potential min-max points

### ISSUE THREAD

**Issue by hyperknot** [JEK58/wprs-forecast#9]
Thanks for making this nice tool!

One feature which would be very valuable is a min-max range for potential points.

max -> if the comp is filled up to full with the pilots on the waiting list with the most WPRS points
min -> filled up with pilots with the least WPRS points

**Comment by JEK58** [comment]
It now shows the potential points as if all registered pilots would be confirmed and the points for the currently confirmed ones.

**Comment by hyperknot** [comment]
I think it doesn't work correctly.

Comp: https://airtribune.com/sxc2023/pilots
150/150 confirmed => the competition is 100% final, there should be no difference between the 2 values.

Yet it says:

PrePWC SkyTribe Hungarian & Moldavian Open 2023

WPRS: 56.4
WPRS if all registered pilots would be confirmed: 68.4
WPRS two valid tasks: 45.1
WPRS one valid task: 28.2
Number of pilots: 150
Number of participants (Pn): 1.2
Participant quality (Pq): 0.47
Comp ranking: 0.564
Number of pilots: 150
Pq_srp: 7871
Pq_srtp: 23354.5
Latest world ranking update: 01/05/2023, 05:05:00

**Comment by JEK58** [comment]
This is an edge case that I'm aware of.
It happens because the potential WPRS take all registered pilots even if that would be more than the comp actually allows. Because at the moment the app does not know what the maximum amount of pilots in a comp is. So when a comp is fully booked the calculation not only uses the confirmed pilots but the unconfirmed as well. Unfortunately it's not so easy to get the max amount of pilots on every comp website as sometimes it's just published in a text.
I was thinking about writing some intelligent parser that can handle this but I'm not sure when it will be ready.

**Comment by JEK58** [comment]
https://github.com/JEK58/wprs-forecast/issues/15

**Comment by hyperknot** [comment]
150 could definitely be a ceiling as that's the max allowed by CIVL. You are right it has to be parsed from each website, but you are already doing that aren't you? I mean for example on Airtribune the value is standard, I don't know civlcomps.

**Comment by JEK58** [comment]
I cut hard-cap it for now at 150, that's right. Will probably do that.
Parsing on Airtribune and civlcomp is easy, but swissleague and PWC is not that easy.

**Comment by hyperknot** [comment]
You are right. I think for a start those two would be nice as they cover most of the comps.

**Comment by JEK58** [comment]
I hard-cap'd it for now at 150. But it will still considere the best 150 pilots registered. A more precise calculation that considers the confirmed pilots and adds the best remaining pilots would need a bigger refactor. (For now;))
